# Generated by Django 5.0.4 on 2024-05-31 21:59

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=35)),
                ('document_id_type', models.IntegerField()),
                ('document_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('user_role', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(default='Not number provided', max_length=12)),
                ('registration_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
