# Generated by Django 5.0.4 on 2024-08-23 15:46

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=35)),
                ('document_id', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('role_type', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(default='Not number provided', max_length=12)),
                ('registration_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_updated', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(default=uuid.UUID('cfd9b8ff-eaa2-4f65-bcc1-9d09a20072fd'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('psid', models.UUIDField(default=uuid.UUID('459f8ec0-682e-4959-a5eb-536ac6d292e3'), editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('facebook', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('tiktok', models.CharField(max_length=300)),
                ('profile_picture', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='psiquepaWEB.user', to_field='psid')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('blog_image', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_updated', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('blog_content', models.CharField(max_length=4500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='psiquepaWEB.user', to_field='psid')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=280)),
                ('workshop_image', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('last_updated', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='psiquepaWEB.user', to_field='psid')),
            ],
        ),
    ]
