# Generated by Django 5.0.4 on 2024-05-31 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='psiquepaWEB.user'),
        ),
    ]
