# Generated by Django 5.0.4 on 2024-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_id_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(),
        ),
    ]
