# Generated by Django 5.0.4 on 2024-05-31 23:08

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0002_blog_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=4500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
