# Generated by Django 5.0.4 on 2024-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0002_alter_user_document_id_type_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(default=1),
        ),
    ]
