# Generated by Django 5.0.4 on 2024-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0003_blog_blog_content_blog_blog_image_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=4500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.CharField(max_length=300),
        ),
    ]
