# Generated by Django 5.0.4 on 2024-04-15 13:16

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0003_alter_user_password_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(max_length=250),
        ),
    ]
