# Generated by Django 5.0.4 on 2024-04-15 13:31

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0004_user_registration_date_alter_user_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
