# Generated by Django 5.0.4 on 2024-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiquepaWEB', '0005_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='Not number provided'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(max_length=15),
        ),
    ]
